# Generated by Django 5.1.7 on 2025-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_project_past_due_date_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='past_due_date',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
